### PR TITLE
QA - links, modals, commas

### LINKED ISSUE #49: QA - links, modals, commas
### 1. Risk label

- Values for risk should not include the text "Risk"  

image

### 2. Stats link

- Click for more stats should direct to stats.opendollar.com

### 3. Vault creation modals

- During creation, modal should say "creating vault" not "modifying vault"
- Once the tx is submitted, the modal text needs to be changed from "Adding a new safe" to "Creating a new vault"

image

### 4. Commas needed across the app

1. Vault row

image

2. Create/edit a vault

image

### 5. Change Accounts to Vaults

image

### 6. Risk is medium, but showing green label 

image

### 7. View button removed from index page

image

Add it to the Account modal

image

Should open this 

image

### PR DESCRIPTION
**Pull request by alekseevaiana**
closes #49 

## What is done
- Updated risk label: removed 'Risk' word and applied function that updates color of the circle
- Stats link changed to stats.opendollar.com
- Creating vault text updated
- Changed Accounts to Vaults
- View btn removed from index page and added to Account Modal
- Formate numbers to strings to show comma separators in Vault Row, Create Vault

### In Vault raw
Screenshot 2023-08-04 at 3 04 48 PM

### In Vault Create
Screenshot 2023-08-07 at 9 44 51 AM

### In Edit mode
Screenshot 2023-08-07 at 12 51 17 PM

### View btn now in Account Modal
Screenshot 2023-08-07 at 9 35 15 AM

### CODE REVIEW

**Review by pi0neerpat — CHANGES_REQUESTED** [review]
image

- Collateral ratio should be formatted
- Liquidation price should be formatted
- Number should only show 8 decimals when in "e-x" format

image

- Inputs should be formatted as well

image

- Green values should also be formatted properly

**Comment by alekseevaiana** [comment]
Updated formatting for liquidation price. (If number is too small (more then 8 zeros after dot) - showing original string). 
Screenshot 2023-08-09 at 9 53 17 AM

**Comment by alekseevaiana** [comment]
Added library `react-number-format` for input. 


https://github.com/UseKeyp/od-app/assets/36742189/2b8cf3e6-61b7-4533-a414-aa7bdd58ae77

**Review by pi0neerpat — APPROVED** [review]
Looks good!

**Pull request merged**
